import Rise from "@/components/marketing/Rise";

export const metadata = { title: "Terms of service — AeroMind AI" };

export default function TermsPage() {
  return (
    <div className="wrap page-top narrow">
      <Rise className="sec-head">
        <p className="eyebrow">Legal</p>
        <h2>Terms of service</h2>
        <p>The agreement between you and AeroMind AI. Last updated 9 August 2026.</p>
      </Rise>
      <Rise className="prose">
        <h3 className="blk">1. Agreement</h3>
        <p>
          By creating an account or using AeroMind, you agree to these terms. If you are agreeing on behalf of
          a company, you confirm you are authorised to do so.
        </p>

        <h3 className="blk">2. Your account</h3>
        <p>
          You must give accurate registration details, keep your password secure, and be at least 18 years
          old. You are responsible for everything that happens under your account, including actions by team
          members you invite.
        </p>

        <h3 className="blk">3. Your data and your rights in it</h3>
        <p>
          You keep all rights in the files you upload and the analyses produced from them. You grant us a
          limited licence to process that data solely to provide the service to you. You confirm you have the
          right to upload the data you provide, including any personal information about your customers.
        </p>

        <h3 className="blk">4. Acceptable use</h3>
        <ul>
          <li>Don&rsquo;t upload data you have no right to use.</li>
          <li>Don&rsquo;t attempt to break, overload, reverse-engineer or gain unauthorised access to the service.</li>
          <li>Don&rsquo;t resell or white-label AeroMind without a written agreement.</li>
          <li>Don&rsquo;t use the service for anything unlawful.</li>
        </ul>

        <h3 className="blk">5. Plans, billing and cancellation</h3>
        <p>
          Paid plans are billed in advance each month unless stated otherwise. Prices are shown on the pricing
          page and may change with 30 days&rsquo; notice. You can cancel at any time; your plan then runs to
          the end of the paid period. Payments already made are non-refundable except where the law requires
          otherwise.
        </p>

        <h3 className="blk">6. About the analysis</h3>
        <p>
          AeroMind produces analysis, suggestions and plans generated by AI from the data you provide. It is
          decision support, not professional financial, legal or accounting advice. Output depends on the
          quality and completeness of your data. You are responsible for reviewing it and for the business
          decisions you make.
        </p>

        <h3 className="blk">7. Availability</h3>
        <p>
          We work to keep AeroMind available and will give notice of planned maintenance where we can, but we
          don&rsquo;t guarantee uninterrupted service.
        </p>

        <h3 className="blk">8. Intellectual property</h3>
        <p>
          The AeroMind software, brand and interface remain ours. These terms give you a right to use the
          service, not to own any part of it.
        </p>

        <h3 className="blk">9. Liability</h3>
        <p>
          To the extent the law allows, we are not liable for lost profits, lost revenue or indirect losses,
          and our total liability in any 12-month period is limited to the amount you paid us in that period.
          Nothing here excludes liability that cannot legally be excluded.
        </p>

        <h3 className="blk">10. Suspension and termination</h3>
        <p>
          We may suspend or close an account that breaches these terms or puts the service or other customers
          at risk. You can close your account at any time from your settings.
        </p>

        <h3 className="blk">11. Changes to these terms</h3>
        <p>
          We will notify you by email before material changes take effect. Continuing to use AeroMind
          afterwards means you accept the updated terms.
        </p>

        <h3 className="blk">12. Contact</h3>
        <p>
          Questions about these terms: <a href="mailto:official@aeromindai.space">official@aeromindai.space</a>.
        </p>
      </Rise>
    </div>
  );
}
